app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /api

auth:
    resource: "@AuthBundle/Resources/config/routing.yml"
    prefix:   /

docs:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /docs/sandbox/index.html

reset_password:
    path: /reset-password
    defaults:
        _controller: AppBundle:User:resetPassword
