# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_PAID_USER:   ROLE_USER
        ROLE_ADMIN:       ROLE_PAID_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        auth_user_provider:
            id: auth.security.user_provider
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        api:
            pattern:    ^/api/
            fos_oauth:  true
            stateless:  true

        main:
            anonymous: ~

    access_decision_manager:
        strategy: unanimous
        allow_if_all_abstain: true

    access_control:
        - { path: ^/api/users/me, method: GET, role: ROLE_USER }
        - { path: ^/api/users$, method: POST, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/purchase, method: PATCH, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/.+/update-token$, method: POST, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/t_.*$, method: PATCH, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, role: ROLE_USER }
