services:
    voter.user.owner:
        class: AppBundle\Security\Authorization\OwnerVoter
        arguments: [[update, delete], AppBundle\Entity\User, null]
        tags:
            - { name: security.voter }

    voter.purchase.owner:
        class: AppBundle\Security\Authorization\OwnerVoter
        arguments: [[update], AppBundle\Entity\PurchaseDate, user]
        tags:
            - { name: security.voter }
